# Enable GPIO Subsystem
CONFIG_GPIO=y

# Enable Console and UART Serial Printing
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_PRINTK=y

# Set System Tick Rate (1000 Hz = 1ms per tick)
CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000