# Enable GPIO Driver subsystem
CONFIG_GPIO=y

# Thread Priority Configuration
CONFIG_NUM_COOP_PRIORITIES=5
CONFIG_NUM_PREEMPT_PRIORITIES=10

# Logging subsystem configuration
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=n
CONFIG_LOG_DEFAULT_LEVEL=3

# Kernel Debugging & Thread Tracking
CONFIG_THREAD_NAME=y